name: Vadim

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Build
        run: |
          git clone --recursive https://github.com/msizanoen1/AltStore
          cd AltStore
          git checkout develop
          cd AltDaemon
          xcodebuild -list -workspace AltStore.xcworkspace
