name: Post Commit to Discord

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Build
        run: |
          cd AltDaemon
          xcrun swift build
