name: Vadim

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Build
        run: |
          set -ex
          git clone --recursive https://github.com/msizanoen1/AltStore
          cd AltStore
          git checkout develop
          xcodebuild -workspace AltStore.xcworkspace -scheme AltSign build
          xcodebuild -workspace AltStore.xcworkspace -scheme AltDaemon build
          tar czvf ../build.tar.gz .
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: build.tar.gz
